export const HOME_ROUTE="/"
export const DASHBOARD_ROUTE="/dashboard"
export const LOGIN_ROUTE="/auth/login"
export const REGISTER_ROUTE="/auth/register"
export const FORGOTPASSWORD_ROUTE="/auth/forgot-password"
